# SPDX-FileCopyrightText: Copyright 2024 Siemens AG
#
# SPDX-License-Identifier: MPL-2.0

name: build browser extension

on:
  push:
    branches:
      - main
      - rel-*
  pull_request:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to checkout the repository
permissions:
  contents: read

env:
  WEB_EXT_VERS: 10.6.0

jobs:
  reuse-and-codestyle:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.14'

      - name: install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y python3-gi pylint python3-pydbus black
          pip3 install --break-system-packages fsfe-reuse
          git clean -f -d

      - name: execute linters
        run: |
          reuse lint
          pylint linux-entra-sso.py

      - name: check Python code formatting
        run: black --diff --check .

      - name: Run biome formatter
        uses: docker://ghcr.io/biomejs/biome:2.4.16@sha256:e43695cefaf3d3dc0713af731ef3ef150fef5a6bf5aebeb0ee3ffbaffd2ddc5e
        with:
          args: ci

  build-xpi:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt update && sudo apt install -y make git zip

      - run: make package deb

      - name: "web-ext lint Firefox"
        run: |
          npx web-ext@${{ env.WEB_EXT_VERS }} lint \
            --source-dir build/firefox \
            --self-hosted \
            --warnings-as-errors

      - name: "web-ext lint Thunderbird"
        run: |
          npx web-ext@${{ env.WEB_EXT_VERS }} lint \
            --source-dir build/thunderbird \
            --self-hosted \
            --warnings-as-errors

      - name: upload Firefox and Thunderbird extension
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: mozilla-xpi
          path: |
            build/**/*.xpi

      - name: upload chrome extension zip
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: chrome-zip
          path: |
            build/chrome/

      - name: upload debian package
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: debian-package
          path: |
            pkgs/linux-entra-sso_*.deb

      - name: attest extension artifacts
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        if: github.event_name == 'push'
        with:
          subject-path: |
            build/Linux-Entra-SSO-v*
            pkgs/linux-entra-sso_*.deb
